### ISSUE TITLE
Killmails layout

### ISSUE THREAD

**Issue by MyUncleSam** [shibdib/Firetail#111]
Hi there,

I think the killmails are not really readable. Can you switch the layout to e.g. the one you use by !about?
I think the tabbed view would make it easier to read the ISK value of the kill.

![grafik](https://user-images.githubusercontent.com/12820919/36975400-41ea7458-207a-11e8-92da-802a03108d44.png)

**Comment by shibdib** [comment]
The issue with the inline columns like that is it looks terrible for mobile users.

**Comment by MyUncleSam** [comment]
We swtiched from Opux to Firetail and as we used Opux noone was unhappy about their tabbed view and I found it better then this one. That is why I ask.
I dont know but maybe it is possible to add something like a switch if the bot should write killmails tabbed or mobile optimized.
