### ISSUE TITLE
Mention user in !auth

### ISSUE THREAD

**Issue by MyUncleSam** [shibdib/Firetail#112]
Hi there,

if you use `!auth` the bot mention the current user and writes the text defined inside the config.

Could you add that everyone mentioned after the `!auth` command is going to be mentioned too?
e.g. `!auth @User` -> `@User To get roles on .....`

Reason:
Some members have no idea how to auth no matter what you write them. If you could let the bot highlight them everything is fine and they authenticate.

**Comment by shibdib** [comment]
Can you give another example of what you're asking for?

**Comment by MyUncleSam** [comment]
At the moment it is only possible to use the `!auth` command without any parameters. In my eyes it would be great if it is possible to mention some users behind which the bot repeats.
E.g.:
User: `!auth @shidbid`
Bot: `@shidbid: Welcome to the server! .......` (whatever in `welcome_string` is in)

So the user immediatly sees that this message is for him. 
I have no idea how I could explain it in other words.

**Comment by shibdib** [comment]
You can just add the auth information to the welcome message
