### ISSUE TITLE
Help system

### ISSUE THREAD

**Issue by MyUncleSam** [shibdib/Firetail#2]
Would be great if it is possible to write short help textes which are stored by the bot.

Examples:

"!help add PI You can find anything according to pi here: https://www.google.de" - this should add a help entry for "PI"
"!help remove PI"
"!help modify PI New text"

Usage should be in this way:
!help PI (searches if there is an exact match and displays it, if not display all *PI* entries - case insensitive)
!help PI @Username (Mentions this user with the result)

Maybe with a special additional shortcut like a single "?":
?PI

**Comment by shibdib** [comment]
Kinda implemented.

You are able to create custom triggers via the config. So you could do a 'PI' trigger and if someone goes !PI it will respond with whatever message you set.
