### ISSUE TITLE
Request: Command for EVE Time conversion

### ISSUE THREAD

**Issue by epoch18** [shibdib/Firetail#48]
Greetings. 

It would be great to see a command like !time or whatever. Some usages could be:

"!time"   =Shows current EVE time
"!time /eve 0600" or "!time /eve 6:00am"   = Shows what EVE time will be when my (local system) time is 0600 of current (unspecified) date. 
"!time /eve 2018-01-23 0600" or "!time /eve 6:00am"   = Shows what EVE time will be when my (local system) time is 0600 of specified date. 

"!time /local 0600"   = Shows what my (local system) time will be when EVE time is 0600 of current (unspecified) date. 
"!time /local 2018-01-23 0600"   = Shows what my (local system) time will be when EVE time is 0600 of specified date. 

Support multiple time formats. "1800", "18:00", "6:00pm", etc. And whatever time format the define in their command should be the format that is returned to them. 

Responses should be detailed to avoid confusion (since EVE time apparently confuses everyone). 
Example: "!time /eve 2018-01-23 0600"
Response: "0600 on January 23, 2018 EVE Time will be 10:00 pm on January 22, 2018 your time. Your local time has been detected as Pacific Daylight Time."

I know I'm getting pretty specific here, but it's the only way I know how to give you detailed requests. Of course it doesn't have to be exactly like this. I'm not even sure if all of this is possible. 

Thank you for your consideration!

**Comment by shibdib** [comment]
See #133
