### ISSUE TITLE
Request: Minimum killboard values

### ISSUE THREAD

**Issue by epoch18** [shibdib/Firetail#82]
Not sure if this already exists for the code base, but I didn't see anything on the public Firetail bot. So..

It would be nice to be able to set a minimum ISK value for kills, and big kills. 

Example:
!addkills corpID 20001    (which would let me ignore naked pod deaths, which I don't really care about. Actually I haven't seen a pod killmail yet so maybe it's already filtering them. )

!addkills big 10000000000     (personally I think a 2bil kill is way too small to be considered "big")

It might also be cool to kind of monitor individual systems by adding system ID recognition to the !addkills command. 

Thanks!

**Comment by shibdib** [comment]
added with https://github.com/shibdib/Firetail/pull/87
