### ISSUE TITLE
Request: Allow choice or kills or losses only for killbot

### ISSUE THREAD

**Issue by epoch18** [shibdib/Firetail#85]
It could be helpful to allow the user to filter out kills or losses from the bot. Pretty straight forward, but...

Example:
!addkills corpID     (normal function)
!addkills corpID kills     (list only kills made by corpID)
!addkills corpID losses     (list only ships lost by corpID)

Thanks!

**Comment by shibdib** [comment]
added with https://github.com/shibdib/Firetail/pull/87
