### ISSUE TITLE
DM for new people on discord server

### ISSUE THREAD

**Issue by nsodsi** [shibdib/Firetail#9]
Would be nice if the bot can give new people on the server a DM how to interact with the bot. the bot looks up his database for discord id and if there is nothing he sends the mail. 
maybe definable by serveradmin if only on first visit or on ever visit and with different message stages

example:
- First visit: "Hi i am firetail, a bot on the server you just entered. for auth go on page xxx.yyy.zzz"

- Secound visit without auth: "hi welcome back to the discord server. you haven't auth yet. if you need help do !help auth"

- third visit with auth: "welcome back pilot. i have serveral other functions. do !help for further informations"

for self hosting ever message editable by admin

**Comment by CokkocZateki** [comment]
and to pm it to a person instead of spamming the chaneel

**Comment by MyUncleSam** [comment]
PM please only as option, for my cases it should stay channel.

**Comment by shibdib** [comment]
Added an initial connection welcome message. The on additional connections idea is too spammy imo
